CREATE TABLE TIPO 
(CODIGO INTEGER PRIMARY KEY, 
DESCRICAO VARCHAR(50));


CREATE TABLE FABRICANTE 
(CODIGO INTEGER PRIMARY KEY,
 RAZAO_SOCIAL VARCHAR (50),
 CNPJ VARCHAR(11),
 TELFIXO VARCHAR(8),
 FAX VARCHAR(10),
 UF CHAR(2) DEFAULT 'RJ');


	CREATE TABLE PRODUTO
(CODIGO INTEGER PRIMARY KEY,
NOME VARCHAR(50),
DESCRICAO VARCHAR(50),
DATA_VALIDADE DATE,
NUM_FABRICANTE INTEGER,
COD_TIPO INTEGER,
VALOR FLOAT(10),

FOREIGN KEY (NUM_FABRICANTE) 
REFERENCES FABRICANTE(CODIGO)
ON DELETE SET NULL ON UPDATE CASCADE,

FOREIGN KEY (COD_TIPO)
REFERENCES TIPO(CODIGO)
ON DELETE SET NULL ON UPDATE CASCADE);



	CREATE TABLE PRODUTO_POR_FABRICANTE
(NÚMERO INTEGER PRIMARY KEY,
NUM_FABRICANTE INTEGER,
VALOR FLOAT(10),

FOREIGN KEY (NUM_FABRICANTE) 
REFERENCES FABRICANTE(CODIGO) 
ON DELETE SET NULL ON UPDATE CASCADE);



	CREATE TABLE TIPO_POR_FABRICANTE
(CODIGO INTEGER PRIMARY KEY,
NUM_FABRICANTE INTEGER, 
COD_TIPO INTEGER,

FOREIGN KEY (NUM_FABRICANTE)
REFERENCES FABRICANTE (CODIGO)
ON DELETE SET NULL ON UPDATE CASCADE,


FOREIGN KEY (COD_TIPO)
REFERENCES TIPO (CODIGO)
ON DELETE SET NULL ON UPDATE CASCADE);



CREATE TABLE COMPRADOR
(MATRICULA INTEGER PRIMARY KEY,
NOME VARCHAR(50),
SEXO CHAR(1) CHECK(SEXO = 'M' OR SEXO = 'F'),
DT_NASC DATE,
FORMACAO VARCHAR(10));



	CREATE TABLE COMPRA
(NUMERO INTEGER PRIMARY KEY,
DT DATE,
COD_PRODUTO INTEGER,
MATR_COMPRADOR INTEGER,
VALOR FLOAT(10),

FOREIGN KEY (COD_PRODUTO)
REFERENCES PRODUTO (CODIGO)
ON DELETE SET NULL ON UPDATE CASCADE,

FOREIGN KEY (MATR_COMPRADOR)
REFERENCES COMPRADOR (MATRICULA)
ON DELETE SET NULL ON UPDATE CASCADE);



	CREATE TABLE HISTORICO_COMPRAS
(CODIGO INTEGER PRIMARY KEY,
MATRICULA_COMPRADOR INTEGER,
NUM_COMPRA INTEGER,

FOREIGN KEY (MATRICULA_COMPRADOR)
REFERENCES COMPRADOR (MATRICULA)
ON DELETE SET NULL ON UPDATE CASCADE,

FOREIGN KEY (NUM_COMPRA)
REFERENCES COMPRA (NUMERO)
ON DELETE SET NULL ON UPDATE CASCADE);



INSERT INTO TIPO VALUES(1, 'Comida');
INSERT INTO TIPO VALUES(2, 'Bebida');
INSERT INTO TIPO VALUES(3, 'Frikace');
INSERT INTO TIPO VALUES(4, 'lasanha');
INSERT INTO TIPO VALUES(5, 'frango');

Select * from tipo;

INSERT INTO FABRICANTE VALUES(7, 'UNIGRANRIO', '10020065598', '20026459', '123456789', 'RJ');
INSERT INTO FABRICANTE VALUES(8, 'PERDIGAO', '10220088598', '20058449', '98766789', 'SP');
INSERT INTO FABRICANTE VALUES(9, 'SADIA', '102888598', '20045449', '98766789', 'MT');
INSERT INTO FABRICANTE VALUES(10, 'FRIBOI', '10220088888', '20999449', '98766789', 'AM');

SELECT * FROM FABRICANTE;

INSERT INTO PRODUTO VALUES(15, 'MORTADELA', 'MUITO BOM', NULL, 9, 1, '9.00');
INSERT INTO PRODUTO VALUES(16, 'CARNE', 'CARNE CONFIAVEL TEM NOME', '05.11.2010', 10, 1, '9.00');
INSERT INTO PRODUTO VALUES(17, 'PAO', 'LEGAL','01.02.1997', 7, 2, '2.00');
INSERT INTO PRODUTO VALUES(18, 'PEIXE', 'DIFERENTE', '11.05.2017', 10, 3, '3.00');

SELECT * FROM PRODUTO;